stages:
  - build
  - test

variables:
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/cypress"

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"

install_dependencies:
  stage: build
  image: node:10
  script:
    - yarn install
  artifacts:
    paths:
      - cache/cypress/
      - node_modules/
  cache:
    paths:
      - cache/cypress/
      - node_modules/

jest:
  stage: test
  image: node:10
  dependencies:
    - install_dependencies
  script:
    - yarn test:unit --passWithNoTests

cypress:
  stage: test
  image: cypress/base:10
  dependencies:
    - install_dependencies
  script:
    - yarn test:e2e --headless
  artifacts:
    when: always
    paths:
      - tests/e2e/screenshots/
      - tests/e2e/videos/
    expire_in: 1 day