stages:
  - build
  - test

variables:
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

install_dependencies:
  stage: build
  image: node:10
  script:
    - yarn install
  artifacts:
    paths:
      - cache/Cypress
      - node_modules/

jest:
  stage: test
  image: node:10
  dependencies:
    - install_dependencies
  script:
    - yarn test:unit

cypress:
  stage: test
  image: cypress/base:10
  dependencies:
    - install_dependencies
  script:
    - yarn test:e2e --headless
  artifacts:
    paths:
      - tests/e2e/screenshots
      - tests/e2e/videos